-- Independent PostgreSQL baseline. Never run against the local SQLite database.
-- Text dates and JSON preserve the source representation during the transfer.
CREATE TABLE roles (slug TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE social_platforms (
  slug TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE,
  oauth_supported INTEGER NOT NULL DEFAULT 1 CHECK (oauth_supported IN (0, 1))
);
CREATE TABLE organizations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, slug TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX organizations_slug_unique ON organizations (lower(slug COLLATE "C"));
CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name TEXT NOT NULL, email TEXT NOT NULL, password_hash TEXT NOT NULL,
  role_slug TEXT NOT NULL REFERENCES roles(slug),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  last_login_at TEXT, default_organization_id INTEGER REFERENCES organizations(id),
  email_verified_at TEXT, mfa_enabled INTEGER NOT NULL DEFAULT 0 CHECK (mfa_enabled IN (0, 1)),
  mfa_secret_encrypted TEXT, mfa_pending_secret_encrypted TEXT,
  mfa_recovery_codes_json TEXT NOT NULL DEFAULT '[]'
);
CREATE UNIQUE INDEX users_email_unique ON users (lower(email COLLATE "C"));
CREATE TABLE organization_members (
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_slug TEXT NOT NULL REFERENCES roles(slug),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (organization_id, user_id)
);
CREATE TABLE sessions (
  token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  csrf_token TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  expires_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  organization_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE TABLE integrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_slug TEXT NOT NULL UNIQUE REFERENCES social_platforms(slug),
  display_name TEXT, client_id TEXT, client_secret_encrypted TEXT,
  access_token_encrypted TEXT, refresh_token_encrypted TEXT, token_expires_at TEXT,
  status TEXT NOT NULL DEFAULT 'not_configured'
    CHECK (status IN ('not_configured', 'configured', 'connected', 'expired', 'error')),
  last_sync_at TEXT, created_by INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  organization_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE TABLE organization_integrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  platform_slug TEXT NOT NULL REFERENCES social_platforms(slug),
  display_name TEXT, client_id TEXT, client_secret_encrypted TEXT,
  status TEXT NOT NULL DEFAULT 'not_configured'
    CHECK (status IN ('not_configured', 'configured', 'connected', 'expired', 'error')),
  last_sync_at TEXT, created_by INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (organization_id, platform_slug)
);
CREATE TABLE oauth_connections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform_slug TEXT NOT NULL REFERENCES social_platforms(slug),
  external_account_id TEXT NOT NULL, display_name TEXT NOT NULL,
  access_token_encrypted TEXT NOT NULL, refresh_token_encrypted TEXT,
  token_type TEXT, token_expires_at TEXT,
  granted_scopes_json TEXT NOT NULL DEFAULT '[]', metadata_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'connected' CHECK (status IN ('connected', 'expired', 'error', 'revoked')),
  last_sync_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  UNIQUE (user_id, platform_slug, external_account_id),
  UNIQUE (organization_id, platform_slug, external_account_id),
  UNIQUE (id, organization_id)
);
CREATE TABLE oauth_states (
  state_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform_slug TEXT NOT NULL REFERENCES social_platforms(slug), expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  organization_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE,
  code_verifier_encrypted TEXT
);
CREATE TABLE social_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_id INTEGER NOT NULL REFERENCES integrations(id) ON DELETE CASCADE,
  external_id TEXT NOT NULL, name TEXT NOT NULL, handle TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  oauth_connection_id INTEGER,
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (oauth_connection_id, organization_id)
    REFERENCES oauth_connections(id, organization_id) ON DELETE CASCADE,
  UNIQUE (integration_id, external_id)
);
CREATE TABLE posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES social_accounts(id) ON DELETE CASCADE,
  external_id TEXT NOT NULL, published_at TEXT NOT NULL, content_type TEXT,
  topic TEXT, campaign TEXT, description TEXT,
  metrics_json TEXT NOT NULL DEFAULT '{}', raw_json TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (account_id, external_id)
);
CREATE TABLE metric_snapshots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES social_accounts(id) ON DELETE CASCADE,
  metric_key TEXT NOT NULL, metric_value DOUBLE PRECISION NOT NULL,
  recorded_at TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'import',
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (account_id, metric_key, recorded_at)
);
CREATE TABLE sync_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_id INTEGER NOT NULL REFERENCES integrations(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
  started_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  completed_at TEXT, records_imported INTEGER NOT NULL DEFAULT 0, error_message TEXT
);
CREATE TABLE oauth_sync_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id INTEGER NOT NULL REFERENCES oauth_connections(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
  started_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  completed_at TEXT, records_imported INTEGER NOT NULL DEFAULT 0, error_message TEXT
);
CREATE TABLE reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL, report_type TEXT NOT NULL DEFAULT 'executive',
  period_start TEXT, period_end TEXT, content_json TEXT NOT NULL,
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE TABLE activity_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL, entity_type TEXT, entity_id TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}', ip_address TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  organization_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE TABLE sync_schedules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  connection_id INTEGER NOT NULL UNIQUE,
  enabled INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  interval_minutes INTEGER NOT NULL DEFAULT 360 CHECK (interval_minutes BETWEEN 15 AND 10080),
  next_run_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  lease_owner TEXT, lease_expires_at TEXT, last_started_at TEXT, last_completed_at TEXT, last_error TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY (connection_id, organization_id)
    REFERENCES oauth_connections(id, organization_id) ON DELETE CASCADE
);
CREATE TABLE login_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_key TEXT NOT NULL,
  attempted_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE auth_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id INTEGER REFERENCES organizations(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL CHECK (purpose IN ('verify_email', 'password_reset', 'mfa_login')),
  token_hash TEXT NOT NULL UNIQUE, metadata_json TEXT NOT NULL DEFAULT '{}',
  expires_at TEXT NOT NULL, consumed_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE email_outbox (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  recipient TEXT NOT NULL, template TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
  attempts INTEGER NOT NULL DEFAULT 0,
  available_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  sent_at TEXT, last_error TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE schema_migrations (name TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL DEFAULT to_char(current_timestamp AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'));

CREATE INDEX idx_users_role ON users(role_slug);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expiry ON sessions(expires_at);
CREATE INDEX idx_sessions_organization ON sessions(organization_id, expires_at);
CREATE INDEX idx_accounts_integration ON social_accounts(integration_id);
CREATE INDEX idx_accounts_organization ON social_accounts(organization_id, id);
CREATE INDEX idx_social_accounts_oauth ON social_accounts(oauth_connection_id);
CREATE INDEX idx_posts_account_date ON posts(account_id, published_at DESC);
CREATE INDEX idx_metrics_account_key_date ON metric_snapshots(account_id, metric_key, recorded_at DESC);
CREATE INDEX idx_sync_integration_date ON sync_runs(integration_id, started_at DESC);
CREATE INDEX idx_reports_creator_date ON reports(created_by, created_at DESC);
CREATE INDEX idx_reports_organization ON reports(organization_id, created_at DESC);
CREATE INDEX idx_activity_user_date ON activity_logs(user_id, created_at DESC);
CREATE INDEX idx_activity_organization ON activity_logs(organization_id, created_at DESC);
CREATE INDEX idx_members_user ON organization_members(user_id, status);
CREATE INDEX idx_integrations_organization ON integrations(organization_id, platform_slug);
CREATE INDEX idx_organization_integrations_platform ON organization_integrations(organization_id, platform_slug);
CREATE INDEX idx_oauth_connections_user ON oauth_connections(user_id, platform_slug, status);
CREATE INDEX idx_oauth_connections_organization ON oauth_connections(organization_id, platform_slug, status);
CREATE INDEX idx_oauth_states_expiry ON oauth_states(expires_at);
CREATE INDEX idx_oauth_states_platform_expiry ON oauth_states(platform_slug, expires_at);
CREATE INDEX idx_oauth_sync_connection ON oauth_sync_runs(connection_id, started_at DESC);
CREATE INDEX idx_sync_schedules_due ON sync_schedules(enabled, next_run_at, lease_expires_at);
CREATE INDEX idx_login_attempts_key_time ON login_attempts(attempt_key, attempted_at);
CREATE INDEX idx_auth_tokens_lookup ON auth_tokens(purpose, token_hash, expires_at);
CREATE INDEX idx_auth_tokens_user ON auth_tokens(user_id, purpose, consumed_at);
CREATE INDEX idx_email_outbox_status ON email_outbox(status, available_at);
